CREATE TABLE 'etat' ('code' TEXT,'nom' TEXT,'PartUSA' TEXT,'Anglais_Off' TEXT);


INSERT INTO etat ( code, nom, PartUSA, Anglais_Off) VALUES 
 ('AL','Alabama','South-East','Yes'), 
 ('AK','Alaska','OTHER','No'), 
 ('AZ','Arizona','South-West','Yes'), 
 ('AR','Arkansas','South-East','Yes'), 
 ('CA','California','South-West','Yes'), 
 ('CO','Colorado','South-West','No'), 
 ('CT','Connecticut','North-East','No'), 
 ('DE','Delaware','North-East','No'), 
 ('DC','District of Columbia','North-East','No'), 
 ('FL','Florida','South-East','Yes'), 
 ('GA','Georgia','South-East','Yes'), 
 ('HI','Hawa�','OTHER','Yes'), 
 ('NH','Hew Hamsphire','North-East','Yes'), 
 ('ID','Idaho','North-West','Yes'), 
 ('IL','Illinois','North-East','Yes'), 
 ('IN','Indiana','North-East','Yes'), 
 ('IA','Iowa','North-East','Yes'), 
 ('KS','Kansas','South-West','Yes'), 
 ('KY','Kentucky','North-East','Yes'), 
 ('LA','Louisiana','South-East','Yes'), 
 ('ME','Maine','North-East','No'), 
 ('MD','Maryland','North-East','No'), 
 ('MA','Massachusetts','North-East','Yes'), 
 ('MI','Michigan','North-East','Yes'), 
 ('MN','Minnesota','North-West','No'), 
 ('MS','Mississippi','South-East','No'), 
 ('MO','Missouri','North-East','No'), 
 ('MT','Montana','North-West','No'), 
 ('NE','Nebraska','South-West','Yes'), 
 ('NV','Nevada','South-West','No'), 
 ('NJ','New Jersey','North-West','No'), 
 ('NM','New Mexico','South-West','No'), 
 ('NY','New-York','North-East','No'), 
 ('NC','North Carolina','South-East','Yes'), 
 ('ND','North Dakota','North-West','Yes'), 
 ('OH','Ohio','North-East','No'), 
 ('OK','Oklahoma','South-West','No'), 
 ('OR','Oregon','North-West','No'), 
 ('PA','Pensylvania','North-East','No'), 
 ('RI','Rhode Island','North-East','No'), 
 ('SC','South Carolina','South-East','Yes'), 
 ('SD','South Dakota','North-West','Yes'), 
 ('TN','Tennessee','South-East','No'), 
 ('TX','Texas','South-West','No'), 
 ('UT','Utah','North-West','Yes'), 
 ('VT','Vermont','North-East','Yes'), 
 ('VA','Virginia','North-East','Yes'), 
 ('WA','Washington','North-East','No'), 
 ('WV','West Virginia','North-East','No'), 
 ('WI','Wisconsin','North-East','No'), 
 ('WY','Wyoming','North-West','Yes');